using System;

namespace forgotten_construction_set
{
	public enum CursorType
	{
		DEFAULT_CURSOR,
		MEDIC_CURSOR,
		LOOT_CURSOR,
		LIFT_CURSOR,
		PICKUP_ITEM_CURSOR,
		ATTACK_CURSOR,
		GUARD_CURSOR,
		TALK_CURSOR,
		SPECIAL_TALK_CURSOR,
		USE_CURSOR,
		TRADER_CURSOR,
		BUILD_CURSOR,
		OPEN_DOOR_CURSOR,
		DOOR_ESCAPE_CURSOR,
		LOCKED_CURSOR,
		PICK_LOCK_CURSOR,
		BUY_HOUSE_CURSOR,
		GREEN_CURSOR,
		MINE_CURSOR,
		REPAIR_CURSOR,
		LIGHT_CURSOR,
		STEAL_CURSOR,
		HAND_CURSOR,
		INVALID_MOVEMENT_CURSOR,
		LOOT_CURSOR_RED,
		KNOCKOUT_CURSOR
	}
}