using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace forgotten_construction_set
{
    public class NativeTranslte
    {
        public static Dictionary<string, string> enumDict;
        public static Dictionary<string, string> sectionDict;
        public static Dictionary<string, string> eventDict;
        static NativeTranslte()

        {
            NativeTranslte.eventDict = new Dictionary<string, string>
            {
                { "EV_CROWD_TRIGGERED","对话事件_人群触发的"},
                { "EV_TAKEN_OVER_PLAYER_TOWN","对话事件_路过玩家城市"},
                { "EV_I_SEE_PLAYER_NICE_BUILDING","对话事件_我看到玩家有一个漂亮的建筑"},
                { "EV_LOST_ARM","对话事件_失去胳膊"},
                { "EV_LOST_LEG","对话事件_失去腿"},
                { "EV_BURNING","对话事件_被灼烧"},
                { "EV_I_SEE_ILLEGAL_PLAYER_BUILDING","对话事件_我看到一个非法的玩家建筑"},
                { "EV_I_SEE_ALLY_PLAYER","对话事件_我看到盟友玩家"},
                { "EV_I_SEE_ENEMY_PLAYER","对话事件_我看到敌对玩家"},
                { "EV_POISON_GAS","对话事件_被闻到毒气瓦斯"},
                { "EV_WINDY","对话事件_遇到大风"},
                { "EV_ACID_WATER","对话事件_遇到酸水"},
                { "EV_ACID_RAIN","对话事件_遇到酸雨"},
                { "EV_ACID_FEET","对话事件_脚步沾到酸"},
                { "EV_GIVE_UP_CHASE","对话事件_放弃追击"},
                { "EV_USING_MY_TRAINING_EQUIPMENT","对话事件_使用我的训练设备"},
                { "EV_KIDNAPPING_MY_ALLY","对话事件_敲晕我的盟友"},
                { "EV_EATING_MY_CROPS","对话事件_吃我的庄家"},
                { "EV_ASSASSINATION_FAILED","对话事件_暗杀失败"},
                { "EV_SLAVE_ESCAPE_OPPORTUNITY_ALONE","对话事件_奴隶独自逃跑的机会"},
                { "EV_SLAVE_ESCAPE_OPPORTUNITY_SAVIOR","对话事件_奴隶逃跑机_救世主"},
                { "EV_WORSHIPING_SOMETHING","对话事件_崇拜祭祀某物"},
                { "EV_EATING_SOMETHING_SOUNDS","对话事件_吃某种东西的声音"},
                { "EV_BOUGHT_ME_FROM_SLAVERY","对话事件_从奴隶商处买了我"},
                { "EV_SQUAD_BROKEN","对话事件_小队溃散了"},
                { "EV_ENTER_TOWN","对话事件_进入城市"},
                { "EV_ENTER_BIOME","对话事件_进入地域"},
                { "EV_ALMOST_WOKE_UP","对话事件_几乎醒了"},
                { "EV_PRISONER_FREE_TO_GO","对话事件_囚犯可以离开了"},
                { "EV_ESCAPED_PRISONER_SPOTTED","对话事件_逃跑的囚犯被发现"},
                { "EV_BOUNTY_SPOTTED","对话事件_有赏金的罪犯被发现"},
                { "EV_WITNESS_THIEF_OR_LOCKPICK","对话事件_目击小偷或开锁人"},
                { "EV_WITNESS_LOOTING_ALLY","对话事件_目击搜刮/抢劫盟友"},
                { "EV_WITNESS_GENERIC_ASSAULT","对话事件_目击一般袭击"},
                { "EV_ESCAPED_EX_SLAVE_SPOTTED","对话事件_逃脱的前奴隶被发现"},
                { "EV_SLAVE_DELIVERY","对话事件_奴隶交付"},
                { "EV_SHOUT_AT_SLAVE_WORKER","对话事件_对奴隶工人大喊大叫"},
                { "EV_RECAPTURED_A_SLAVE","对话事件_夺回一个奴隶"},
                { "EV_ESCAPING_SLAVE_SPOTTED","对话事件_正在逃跑的奴隶被发现"},
                { "EV_INTRODUCING_NEW_SLAVE","对话事件_介绍新奴隶"},
                { "EV_I_SEE_UNIFORM_IMPOSTER","对话事件_我看见一名冒名顶替者"},
                { "EV_LOOTING_EVERYTHING","对话事件_正在抢劫/掠夺任何东西"},
                { "EV_LOOTING_WEAPON_ONLY","对话事件_正在抢劫/掠夺武器"},
                { "EV_BETRAYAL","对话事件_暴露"},
                { "EV_CONTRACT_JOB_ENDED","对话事件_合约到期"},
                { "EV_SPEECH_INTERRUPTED_ATTACKED_BY_STRANGERS","对话事件_讲话被陌生人攻击打断"},
                { "EV_SPEECH_INTERRUPTED_ATTACKED_BY_TARGET","对话事件_讲话被目标攻击打断"},
                { "EV_I_SEE_ANIMAL_SQUAD","对话事件_我看到一个动物小队"},
                { "EV_HARRASSMENT_SHOUTS","对话事件_骚扰时呼喊"},
                { "EV_GET_UP_UNNECCESSARY_FIGHT","对话事件_起来参加非必要的战斗"},
                { "EV_GET_UP_FIGHT","对话事件_起来战斗"},
                { "EV_GET_UP_PEACE","对话事件_起来和平"},
                { "EV_FIRSTAID_KIT_EMPTY","对话事件_没有急救物品了"},
                { "EV_BEING_HEALED_FINISHED","对话事件_被治疗结束"},
                { "EV_HEALING_OTHER_FINISHED","对话事件_治疗他人结束"},
                { "EV_BEING_HEALED_START","对话事件_开始被治疗"},
                { "EV_HEALING_OTHER_START","对话事件_治疗他人开始"},
                { "EV_INTRUDER_FOUND","对话事件_找到了入侵者"},
                { "EV_LAUNCH_ATTACK","对话事件_挑起攻击"},
                { "EV_I_DEFEATED_SQUAD","对话事件_我打败了队伍"},
                { "EV_UNLOCK_MY_CAGE_ATTEMPT","对话事件_试图打开我的笼子"},
                { "EV_UNLOCK_MY_CAGE_OR_SHACKLES","对话事件_打开我的笼子或者脚镣"},
                { "EV_BAR_TALK","对话事件_就把谈话"},
                { "EV_SCREAMING_TORTURE","对话事件_折磨尖叫"},
                { "EV_MARKED_FOR_DEATH","对话事件_标记为死亡"},
                { "EV_SHOO_FROM_MY_BUILDING","对话事件_从我的建筑内驱赶"},
                { "EV_THIEF_CAUGHT_STEALING_FROM_ME","对话事件_小偷偷我东西被抓住了"},
                { "EV_SOUND_THE_ALARM","对话事件_听到警报"},
                { "EV_I_SEE_RAGDOLL","对话事件_我见到尸体"},
                { "EV_I_SEE_NEUTRAL_SQUAD","对话事件_我看到中立队伍"},
                { "EV_ANNOUNCEMENT","对话事件_声明"},
                { "EV_PLAYER_TALK_TO_ME","对话事件_玩家与我对话"},
            };

            NativeTranslte.sectionDict = new Dictionary<string, string>
            {
                { "0 - base","0-基础"},
                { "1 - slope","1-斜坡"},
                { "2 - cliff","2-悬崖"},
                { "3 - grass","3-草地"},
                { "4 - dirt","4-尘土"},
                { "5 - road","5-道路"},
                { "AI","AI"},
                { "Appearance","外观"},
                { "Audio","声音"},
                { "Base","基本"},
                { "Blending","混合"},
                { "CONDITIONS","对话条件"},
                { "Choosefrom list","可选择列表"},
                { "Colouring","色彩"},
                { "Dust","灰尘"},
                { "Effects","效果"},
                { "Fog","雾"},
                { "GAME SPEEDS","游戏速度"},
                { "General","通用"},
                { "Global balance","全局平衡"},
                { "Lighting","灯光"},
                { "Material","材料"},
                { "Movement","移动"},
                { "Other","其他"},
                { "Performance","性能"},
                { "Position","坐标"},
                { "Respawn","刷新&重生"},
                { "Sky","天空"},
                { "Sun","太阳"},
                { "Time","时间"},
                { "Time of Day","每天时间"},
                { "View","查看"},
                { "Weather","天气"},
                { "Wind","风"},
                { "affects characters","影响角色"},
                { "ammo","弹药"},
                { "animation","动画"},
                { "armour vendor quality chance","装甲供应商质量机率"},
                { "attributes","属性"},
                { "audio","音乐&&声音"},
                { "big stuff","重大问题"},
                { "block success","格挡成功"},
                { "blood","血"},
                { "bounty","赏金"},
                { "building","建筑"},
                { "building improvements","建筑改进"},
                { "category","类别"},
                { "child foliage","子植被"},
                { "clustering","群集"},
                { "collision","碰撞"},
                { "coloring","着色"},
                { "combat","战斗"},
                { "combat balance","战斗平衡"},
                { "combat damage","战斗伤害"},
                { "combat skills","战斗技能"},
                { "construction","施工"},
                { "content","内容"},
                { "coverage resources","覆盖资源"},
                { "craft","工艺"},
                { "damage","伤害"},
                { "damage effects 0-1","伤害效果0-1"},
                { "death","死亡"},
                { "details","详情"},
                { "distribution","分布"},
                { "distribution 2","分布2"},
                { "doors","门"},
                { "editor","编辑器"},
                { "end result","最终结果"},
                { "energy","能量"},
                { "entry/exit","进入/离开"},
                { "faction","阵营"},
                { "farming","农艺"},
                { "files","文件"},
                { "flee","逃跑"},
                { "footprint","足迹"},
                { "function","作用/效果/函数"},
                { "general","常规"},
                { "grass","植被"},
                { "growth","生长"},
                { "gun stuff","枪的东西"},
                { "harvest","收割"},
                { "head overlay","头部覆盖"},
                { "hits","打击"},
                { "hunger","饥饿"},
                { "idle","待机"},
                { "injury 0-100","受伤0-100"},
                { "inventory","仓储"},
                { "inventory icon","仓储图标"},
                { "item","项目"},
                { "items","物品"},
                { "layout","布局"},
                { "leaders","队长"},
                { "levels","等级"},
                { "life","生命"},
                { "linking","链接"},
                { "locked","已锁住"},
                { "locks","锁"},
                { "main","主要的"},
                { "map","地图"},
                { "material","材质"},
                { "medic","医药"},
                { "medical","医疗"},
                { "mesh","网格"},
                { "mod","修改"},
                { "money","金钱"},
                { "movement","移动相关"},
                { "nests","巢穴"},
                { "node","节点"},
                { "offsetting","偏移量"},
                { "overrides","覆盖"},
                { "physics","物理的"},
                { "placement","安置"},
                { "portrait","肖像"},
                { "position","坐标的"},
                { "positioning","定位"},
                { "prices","价格"},
                { "properties","位置"},
                { "race damage","种族伤害"},
                { "ragdoll","布娃娃系统"},
                { "rank","等级"},
                { "relation","关系"},
                { "repeats","重复"},
                { "resources","资源"},
                { "scale","缩放"},
                { "science skills","科学技能"},
                { "second mesh","第二网格"},
                { "security","安全"},
                { "settings","设置"},
                { "shadows","阴影"},
                { "size","尺寸"},
                { "skill bonus","技能点"},
                { "skills","点数"},
                { "skin","皮肤"},
                { "spawn","投放/刷新"},
                { "spawn junk","投放垃圾"},
                { "special","特别的"},
                { "spotlight","聚光灯"},
                { "stats","状态"},
                { "stats 0-1","状态0-1"},
                { "stats arms","胳膊状态"},
                { "stats legs","腿部状态"},
                { "stats mod","状态修啊"},
                { "stealth skills","潜行技能"},
                { "stone","石材"},
                { "stumble","跌倒"},
                { "tags","标签"},
                { "tags always","很可能有标签"},
                { "tags common","一般可能有标签"},
                { "tags never","不可能有标签"},
                { "tags rare","罕见的标签"},
                { "tech","技术"},
                { "territorial trigger","领土上出现"},
                { "text","文字"},
                { "texture layers","贴图层"},
                { "timer","计时器"},
                { "town residents","城市居民"},
                { "track exclusion","track exclusion"},
                { "trade skills","商业技能"},
                { "type","类型"},
                { "vendors","供应商"},
                { "visual","虚拟"},
                { "water","水"},
                { "weapon skills","武器技能"},
                { "weather","天气"},
                { "weight","重量"},
                { "what is","这是"},
                { "xp","经验"},
            };
            NativeTranslte.enumDict = new Dictionary<string, string> {
                { "DC_HAS_ROBOT_LIMBS","对话条件_有机械肢体"},
                { "DC_HAS_AI_CONTRACT","对话条件_有AI合约"},
                { "DC_IS_RECRUITABLE","对话条件_可以招募"},
                { "DC_TARGET_CHARACTER_EXISTS","对话条件_目标角色存在"},
                { "DC_IN_A_PLAYER_TOWN","对话条件_在玩家城市里"},
                { "DC_PLAYERS_BEST_TOWN_LEVEL","对话条件_玩家城市最高级别"},
                { "DC_TOWN_LEVEL_CURRENT_LOCATION","对话条件_当地城市的级别"},
                { "DC_MIXED_GENDER_GROUP","对话条件_混合队伍"},
                { "DC_STARVING","对话条件_饥饿中"},
                { "DC_USING_MY_TRAINING_EQUIPMENT","对话条件_正在使用我的训练器材"},
                { "DC_HAS_ILLEGAL_ITEM","对话条件_拥有违禁品"},
                { "DC_IS_INDOORS","对话条件_在后门/房子内"},
                { "DC_IS_SNEAKING","对话条件_偷偷摸摸的/潜行中"},
                { "DC_CAN_AFFORD_BOUNTY","对话条件_能负担得起的赏金"},
                { "DC_IS_SAME_RACE_AS_ME","对话条件_与我同种族"},
                { "DC_WEARING_LOCKED_SHACKLES","对话条件_穿着锁起来的脚镣/手铐"},
                { "DC_IS_IN_LOCKED_CAGE","对话条件_在上锁的囚笼里"},
                { "DC_IS_ESCAPED_SLAVE","对话条件_是逃跑的奴隶"},
                { "DC_TARGET_IS_SLAVE_OF_MY_FACTION","对话条件_目标是我阵营的奴隶"},
                { "DC_HAS_A_BASE_NEARBY","对话条件_在附近有基地"},
                { "DC_IS_SLAVE","对话条件_是奴隶"},
                { "DC_TOWN_WALLS_LOCKED_UP","对话条件_城市城墙已锁"},
                { "DC_WITHIN_TOWN_WALLS","对话条件_城市的墙内"},
                { "DC_IN_COMBAT","对话条件_在战斗中"},
                { "DC_I_SHOULD_HELP_THIS_GUY","对话条件_我应该帮这个人"},
                { "DC_I_SHOULD_SCREW_THIS_GUY_OVER","对话条件_我应该欺负这个人"},
                { "DC_I_HATE_THIS_GUY","对话条件_我讨厌这个人"},
                { "DC_I_LOVE_THIS_GUY","对话条件_我喜欢这个人"},
                { "DC_MY_MISSION_IS_FRIENDLY","对话条件_我的任务很友好"},
                { "DC_TARGET_IS_MY_MISSION_TARGET","对话条件_目标是我的任务目标"},
                { "DC_TOWN_HAS_FORTIFICATIONS_WALLS","对话条件_城里有防御工事"},
                { "DC_IM_UNARMED","对话条件_我手无寸铁"},
                { "DC_BOUNTY_AMOUNT_ACTUAL","对话条件_BOUNTY_AMOUNT_ACTUAL"},
                { "DC_CARRYING_SOMEONE_TO_ENSLAVE","对话条件_正扛着某人去当作奴隶"},
                { "DC_IS_FEMALE","对话条件_是女人"},
                { "DC_IS_DEAD","对话条件_已死"},
                { "DC_SQUAD_IS_DOWN","对话条件_队伍已倒/已挂"},
                { "DC_IS_NEARLY_KO","对话条件_就快昏迷"},
                { "DC_IS_KO","对话条件_已经昏迷"},
                { "DC_BOUNTY_AMOUNT_PERCEIVED","对话条件_赏金数额被认为"},
                { "DC_IS_OUTNUMBERED","对话条件_人数数量已超过"},
                { "DC_SQUAD_ONLY_ANIMALS","对话条件_队伍只有动物"},
                { "DC_NUM_BACKPACKS","对话条件_背包数量"},
                { "DC_IS_PLAYER","对话条件_是玩家"},
                { "DC_SQUAD_SIZE","对话条件_队伍大小"},
                { "NULL_NULL_____DC_TARGET_SQUAD_SIZE","对话条件_目标队伍大小"},
                { "DC_COPS_AROUND","对话条件_四周有警察"},
                { "DC_IS_RUNNING","对话条件_正在跑"},
                { "DC_IN_A_NON_PLAYER_TOWN","对话条件_在非玩家城市内"},
                { "DC_NEARLY_KO","对话条件_差点昏倒"},
                { "DC_DAMAGED_HEAD","对话条件_头部受伤"},
                { "DC_BROKEN_ARM","对话条件_胳膊损坏"},
                { "DC_BROKEN_LEG","对话条件_腿损坏"},
                { "DC_PERSONALITY_TAG","对话条件_个人性格标签"},
                { "DC_IS_ENEMY","对话条件_是敌人"},
                { "DC_IS_ALLY","对话条件_是盟友"},
                { "DC_HAS_TAG","对话条件_具有标签"},
                { "DC_RELATIONS","对话条件_关系/友好度"},
                { "DC_PLAYERMONEY","对话条件_玩家的金钱数"},
                { "DC_REPUTATION","对话条件_信用度"},
                { "DC_CARRYING_BOUNTY_ALIVE","对话条件_正抬着或者的赏金犯人"},
                { "DC_CARRYING_BOUNTY_DEAD","对话条件_正抬着死了的赏金犯人"},
                { "DC_IMPRISONED_BY_TARGET","对话条件_已被目标囚禁"},
                { "DC_IMPRISONED_BY_OTHER","对话条件_已被其他人囚禁"},
                { "DC_IS_A_TRADER","对话条件_是商人"},
                { "DC_FACTION_RANK","对话条件_在阵营的等级"},
                { "DC_BUILDING_IS_CLOSED_AND_SECURED","对话条件_建筑已关闭并且是私人的"},
                { "DC_PLAYER_TECH_LEVEL","对话条件_玩家的技术等级"},
                { "DC_NUM_DIALOG_EVENT_REPEATS","对话条件_对话时间的重复数量"},
                { "DC_IS_IMPRISONED","对话条件_已被囚禁"},
                { "DC_IMPRISONMENT_IS_DEATHROW","对话条件_被囚禁的人在死囚区"},
                { "DC_TARGET_IN_TALKING_RANGE","对话条件_目标在可对划范围内"},
                { "DC_IN_MY_BUILDING","对话条件_在我的建筑内"},
                { "DC_TARGET_LAST_SEEN_X_HOURS_AGO","对话条件_最后一次见到目标在几小时前"},
                { "DC_IS_LEADER","对话条件_是队长"},
                { "DC_WEAKER_THAN_ME","对话条件_比我要弱"},
                { "DC_STRONGER_THAN_ME","对话条件_比我要强"},
                { "STAT_SMITHING_BOW","状态属性_制作弩弓"},
                { "STAT_LOCKPICKING","状态属性_开锁"},
                { "STAT_FRIENDLY_FIRE","状态属性_误射"},
                { "STAT_CROSSBOWS","状态属性_弩弓"},
                { "STAT_POLEARMS","状态属性_长柄武器"},
                { "STAT_SURVIVAL","状态属性_生还"},
                { "STAT_DODGE","状态属性_闪避"},
                { "STAT_MASSCOMBAT","状态属性_集团战斗"},
                { "STAT_MARTIALARTS","状态属性_武术"},
                { "STAT_BLUNT","状态属性_钝器"},
                { "STAT_HEAVYWEAPONS","状态属性_重武器"},
                { "STAT_SABRES","状态属性_军刀"},
                { "STAT_KATANAS","状态属性_武士刀"},
                { "STAT_PERCEPTION","状态属性_感知"},
                { "STAT_SWIMMING","状态属性_游泳"},
                { "STAT_ASSASSINATION","状态属性_刺杀"},
                { "STAT_TOUGHNESS","状态属性_韧性"},
                { "STAT_WEAPONS","状态属性_武器"},
                { "STAT_MELEE_DEFENCE","状态属性_近战防御"},
                { "STAT_DEXTERITY","状态属性_敏捷"},
                { "STAT_ATHLETICS","状态属性_跑步"},
                { "STAT_STEALTH","状态属性_潜行"},
                { "STAT_VET","状态属性_兽医"},
                { "STAT_HIVEMEDIC","状态属性_蜂巢医疗"},
                { "STAT_COOKING","状态属性_烹饪"},
                { "STAT_FARMING","状态属性_农业"},
                { "STAT_TURRETS","状态属性_炮塔"},
                { "STAT_THIEVING","状态属性_小偷"},
                { "STAT_MEDIC","状态属性_医疗"},
                { "STAT_SMITHING_ARMOUR","状态属性_制作装甲"},
                { "STAT_SMITHING_WEAPON","状态属性_制作武器"},
                { "STAT_ROBOTICS","状态属性_机器人技术"},
                { "STAT_ENGINEERING","状态属性_工程师"},
                { "STAT_SCIENCE","状态属性_科学家"},
                { "STAT_LABOURING","状态属性_劳作"},
                { "STAT_MELEE_ATTACK","状态属性_近战攻击"},
                { "STAT_STRENGTH","状态属性_力量"},
               
                { "SIGNAL_NONE","信号_无信号"},
                { "SIG_RETREAT_CANNIBAL_RAID","信号_食人族突袭撤退"},
                { "SIG_AT_SAFE_TOWN","信号_在安全的城市"},
                { "SIG_AT_HOME_TOWN","信号_在自己家的城市"},
                { "SIG_CANNIBAL_START_PATROL","信号_食人族开始巡逻"},
                { "SIG_SQUAD_NOT_INTACT","信号_队伍不完整"},
                { "SIG_START_PATROL","信号_开始巡逻"},
                { "SIG_DIPLOMAT_MISSION","信号_外交任务"},
                { "SIG_DEFEAT_SQUAD","信号_打败队伍"},
                { "SIG_HOME_OWNER_KEEP_LOCKED","信号_业主已上锁"},
                { "SIG_GATHER_UP_ALL_LOCAL_PRISONERS","信号_聚集所有当地的囚犯"},
                { "SIG_SLAVER_SHIP_TO_WORKCAMPS","信号_遣送奴隶去工作营地"},
                { "SIG_BODYGUARD","信号_保镖"},
                { "SIG_BECOME_EX_SLAVE","SIG_BECOME_EX_SLAVE"},
                { "SIG_OUT_OF_DANGER","信号_脱离危险"},
                { "SIG_DEFEND_PLAYER_TOWN_TIMED","信号_防守玩家城市_计时"},
                { "SIG_WANDERING_TOWN_TO_TOWN","信号_从一个城市到另一个城市"},
                { "SIG_HANG_OUT_AT_BAR","信号_泡吧"},
                { "SIG_RAIDING_WEAK_VILLAGES","信号_袭击软弱的村庄"},
                { "WAR_GATHER_FORCES","信号_战争聚集力量"},
                { "WAR_ASSAULT_TOWN","信号_战争袭击城市"},
                { "WAR_BATTLE_MEETING","信号_战役会面"},
                { "SIG_REFUGEE_DISBAND","信号_难民解散"},
                { "SIG_START_PATROL_RUNNING","信号_开始巡逻_跑步"},
                { "SIG_GATHER_UP_ALL_LOCAL_PRISONERS_UNHOLY","信号_聚集所有的非圣国的本地囚犯"},
                { "SIG_RETREAT_CANNIBAL_RAID_TO_NEAREST_NEST","信号_撤退食人族突袭到最近的巢穴"},
                { "SIG_HANG_OUT_OUTDOORS_ONLY","信号_只在户外活动"},
                { "SIG_CANNIBALS_AT_HOME","信号_食人族在家"},
                { "SIG_SLAVER_SHIP_TO_ANYWHERE_CLOSE","信号_遣送奴隶到附近的任何地方"},
                { "SIG_PASSING_BY_TOWN_ASSAULT","信号_攻击路过的城市"},
                { "SIG_OCCUPY_CONQUERED_TOWN","信号_恶意占领城市"},
                { "SIG_DEFEND_PLAYER_TOWN_CAMPAIGN","信号_保卫玩家城市战役"},
                { "WAR_ASSAULT_TOWN_CANNIBAL","信号_战争_攻击城市_食人族"},
                { "SIG_TIMED_CONTRACT","信号_计时合约"},


                { "GEAR_CLOTH","装甲-布甲"},
                { "GEAR_LIGHT_轻甲","装甲-轻甲"},
                { "GEAR_MEDIUM","装甲-中甲"},
                { "GEAR_HEAVY","装甲-重甲"},
                { "GEAR_MAX","装甲-最大"},
                { "GEAR_PROTOTYPE","盔甲_基础"},
                { "GEAR_CHEAP","盔甲_片面"},
                { "GEAR_STANDARD","盔甲_标准"},
                { "GEAR_GOOD","盔甲_良好"},
                { "GEAR_QUALITY","盔甲_专业"},
                { "GEAR_MASTER","盔甲_大师"},
                { "CLOTH","CLOTH_衣服"},
                { "LEATHER","皮甲"},
                { "CHAIN","链甲"},
                { "METAL_PLATE","板甲"},

                { "TP_JUST_ACTION","TP_仅动作"},
                { "TP_FLUFF","TP_悠闲"},
                { "TP_NON_URGENT","TP_非紧急"},
                { "TP_URGENT","TP_紧急"},
                { "TP_OBEDIENCE","TP_服从"},
                { "TP_MAX_SIZE","TP_最大数量"},

                { "T_ME","T_我自己"},
                { "T_TARGET","T_目标"},
                { "T_TARGET_IF_PLAYER","T_如果目标是玩家"},
                { "T_INTERJECTOR1","T_插话者1"},
                { "T_INTERJECTOR2","T_插话者2"},
                { "T_INTERJECTOR3","T_插话者3"},
                { "T_WHOLE_SQUAD","T_整个队伍"},
                { "T_TARGET_WITH_RACE","T_目标和种族"},


                { "TOWN_NEST","城_巢穴"},
                { "TOWN_OUTPOST","城_哨站"},
                { "TOWN_TOWN","城_城市"},
                { "TOWN_VILLAGE","城_村庄"},
                { "TOWN_RUINS","城_废墟"},
                { "TOWN_SLAVE_CAMP","城_奴隶营地"},
                { "TOWN_MILITARY","城_军营"},
                { "TOWN_PRISON","城_囚犯营地"},
                { "TOWN_NEST_MARKER","城_巢穴标记"},
                { "TOWN_POI","城_信息点"},
                { "TOWN_NULL","城_无效"},
              
                { "BD_NONE","BD_空"},
                { "BD_SHOP","BD_商店"},
                { "BD_BARRACKS","BD_军营"},
                { "BD_BAR","BD_酒吧"},
                { "BD_HOSPITAL","BD_医院"},
                { "BD_ARMOURY","BD_兵工厂"},
                { "BD_TREASURE","BD_财宝"},
                { "BD_PRISON","BD_囚犯"},
                { "BD_HQ","BD_总部"},
                { "BD_RESIDENTIAL","BD_住宅"},
                { "BD_SLAVE_STORAGE","BD_囚犯存储"},
                { "BD_RESIDENTIAL_SMALL","BD_小住宅"},

                { "BF_ANY","BF_任何"},
                { "BF_MINE","BF_采矿"},
                { "BF_RESOURCE_STORAGE","BF_资源存储"},
                { "BF_RESEARCH","BF_研究"},
                { "BF_REFINERY","BF_精炼"},
                { "BF_GENERATOR","BF_发电"},
                { "BF_BED","BF_床"},
                { "BF_TRAINING","BF_训练"},
                { "BF_CAGE","BF_囚笼"},
                { "BF_SHOP","BF_商店"},
                { "BF_CRAFTING","BF_生产"},
                { "BF_CORPSE_DISPOSAL","BF_遗体处置"},
                { "BF_TURRET","BF_炮台"},
                { "BF_GENERAL_STORAGE","BF_通用存储"},
                { "BF_ITEM_FURNACE","BF_焚烧炉"},
                { "BF_LIGHT","BF_灯"},
                { "BF_TABLE","BF_桌子"},
                { "BF_CHAIR","BF_椅子"},
                { "BF_FLUFF","BF_无价值的"},
                { "BF_SHELL_WITH_INTERIOR","BF_SHELL_WITH_INTERIOR"},
                { "BF_WALL","BF_墙"},
                { "BF_GATE","BF_大门"},
                { "BF_DOOR","BF_门"},
                { "BF_BATTERY","BF_电池"},
                { "BF_THRONE","BF_王座"},
                { "BF_SKELETON_BED","BF_骨人床"},
                { "BF_RAIN_COLLECTOR","BF_雨水收集器"},
                { "BF_MINE_NATURAL","BF_开采野生矿"},
                { "BF_GENERATOR_WIND","BF_风力发电机"},

                { "ANIM_NORMAL","动物_普通"},
                { "ANIM_IMPRISONED","动物_被囚禁"},
                { "ANIM_SLEEPING","动物_睡觉"},
                { "ANIM_CARRIED","动物_被抬着"},
                { "ANIM_SWIMMING","动物_游泳"},
                { "ANIM_GROUNDED","动物_在队列里"},
                { "ANIM_COMBAT","动物_在战斗"},
                { "ANIM_ATTACKS","动物_攻击"},
                { "ANIM_RANGED","动物_被射击"},

                { "LT_NONE","标签_无"},
                { "LT_MY_INTRUDER","标签_我的入侵者"},
                { "LT_MY_LIFESAVER","标签_我的救命恩人"},
                { "LT_FREED_ME","标签_解放了我"},
                { "LT_STOLE_FROM_ME","标签_曾偷过我东西"},
                { "LT_MY_CAPTOR","标签_曾俘虏过我"},
                { "LT_FRIENDLY_AQUAINTANCE","标签_友好的熟人"},
                { "LT_DEFEATED_MY_SQUAD_ONCE","标签_曾打败过我的队伍"},
                { "LT_SQUAD_LOST_TO_ME_ONCE","标签_队伍曾经被我打败过"},
                { "LT_KILLED_MY_FRIEND","标签_曾杀死过我的朋友"},
                { "LT_I_SCREWED_THIS_GUY","标签_我绑架过这个人"},
                { "LT_MAX","标签_最大"},
              
                { "OT_NONE","职业_无"},
                { "OT_LAW_ENFORCEMENT","职业_执法者"},
                { "OT_MILITARY","职业_军人"},
                { "OT_TRADER","职业_商人"},
                { "OT_CIVILIAN","职业_市民"},
                { "OT_DIPLOMAT","职业_外交人员"},
                { "OT_SLAVE","职业_奴隶"},
                { "OT_SLAVER","职业_努力商人"},
                { "OT_BANDIT","职业_强盗"},
                { "OT_ADVENTURER","职业_游侠"},
                { "OT_END","职业_结束"},
                
                { "CUT_DEFAULT","砍杀方向_默认"},
                { "CUT_DOWNWARD","砍杀方向_向下"},
                { "CUT_LEFT","砍杀方向_左"},
                { "CUT_RIGHT","砍杀方向_右"},
                { "CUT_THRUST","砍杀方向_用力推"},
                { "CUT_UPWARDS","砍杀方向_向上"},
                { "CUT_PIERCED","砍杀方向_刺穿"},
                { "CUT_REAR_DOWNWARD","砍杀方向_后下"},
                { "CUT_REAR_LEFT","砍杀方向_后左"},
                { "CUT_REAR_RIGHT","砍杀方向_后右"},
               
                { "FRONT","来源_前"},
                { "REAR","来源_后"},
                { "LEFTSIDE","来源_左侧"},
                { "RIGHTSIDE","来源_右侧"},
               
                { "DA_NONE","对话动作_无"},
                { "DA_TRADE","对话动作_交易"},
                { "DA_TALK_TO_LEADER","对话动作_与队长说话"},
                { "DA_JOIN_SQUAD_WITH_EDIT","对话动作_加入小队并编辑"},
                { "DA_AFFECT_RELATIONS","对话动作_影响友好度"},
                { "DA_AFFECT_REPUTATION","对话动作_影响信誉"},
                { "DA_ATTACK_CHASE_FOREVER","对话动作_跟随攻击永远"},
                { "DA_GO_HOME","对话动作_回家"},
                { "DA_TAKE_MONEY","对话动作_拿钱出来"},
                { "DA_GIVE_MONEY","对话动作_给钱"},
                { "DA_PAY_BOUNTY","对话动作_支付赏金"},
                { "DA_CHARACTER_EDITOR","对话动作_角色编辑"},
                { "DA_FORCE_SPEECH_TIMER","对话动作_强制说话时间"},
                { "DA_DECLARE_WAR","对话动作_宣战"},
                { "DA_END_WAR","对话动作_结束战争"},
                { "DA_CLEAR_AI","对话动作_清除AI"},
                { "DA_FOLLOW_WHILE_TALKING","对话动作_当对话的时候跟随对方"},
                { "DA_THUG_HUNTER","对话动作_单挑"},
                { "DA_JOIN_SQUAD_FAST","对话动作_快速加入队伍"},
                { "DA_REMEMBER_CHARACTER","对话动作_记住角色"},
                { "DA_FLAG_TEMP_ALLY","对话动作_标记为临时盟友"},
                { "DA_FLAG_TEMP_ENEMY","对话动作_标记为临时敌人"},
                { "DA_MATES_KILL_ME","对话动作_好友杀死我"},
                { "DA_MAKE_TARGET_RUN_FASTER","对话动作_让目标跑的更快"},
                { "DA_GIVE_TARGET_MY_SLAVES","对话动作_给目标我的奴隶"},
                { "DA_TAG_ESCAPED_SLAVE","对话动作_标记为逃跑的奴隶"},
                { "DA_FREE_TARGET_SLAVE","对话动作_释放对方的奴隶"},
                { "DA_MERGE_WITH_SIMILAR_SQUADS","对话动作_与类似的小队合并"},
                { "DA_SEPARATE_TO_MY_OWN_SQUAD","对话动作_从我的小队分离出来"},
                { "DA_ARREST_TARGET","对话动作_逮捕目标"},
                { "DA_ARREST_TARGETS_CARRIED_PERSON","对话动作_逮捕目标抬着的人"},
                { "DA_ATTACK_TOWN","对话动作_攻击城市"},
                { "DA_ASSIGN_BOUNTY","对话动作_指派赏金"},
                { "DA_CRIME_ALARM","对话动作_犯罪警报"},
                { "DA_RUN_AWAY","对话动作_逃跑"},
                { "DA_INCREASE_FACTION_RANK","对话动作_提升阵营中的等级"},
                { "DA_LOCK_THIS_DIALOG","对话动作_锁定这个对话"},
                { "DA_ASSAULT_PHASE","对话动作_攻击阶段"},
                { "DA_RETREAT_PHASE","对话动作_撤退阶段"},
                { "DA_VICTORY_PHASE","对话动作_访问阶段"},
                { "DA_ENSLAVE_TARGETS_CARRIED_PERSON","对话动作_把目标抬着的人变为奴隶"},
                { "CHOOSE_SLAVES_SELLING","对话动作_选择奴隶出售"},
                { "CHOOSE_SLAVES_BUYING","对话动作_选择努力购买"},
                { "CHOOSE_PRISONER_BAIL","对话动作_选择囚犯保释"},
                { "CHOOSE_CONSCRIPTION","对话动作_选择征兵"},
                { "CHOOSE_RECRUITING","对话动作_选择招募"},
                { "CHOOSE_HIRING_CONTRACT","对话动作_选择雇佣合约"},
                { "SURRENDER_NON_HUMANS","对话动作_交出所有非人类"},
                { "CHOOSE_ANIMALS_BUYING","对话动作_选择动物购买"},
                { "DA_CLEAR_BOUNTY","对话动作_清除赏金"},
                { "DA_PLAYER_SELL_PRISONERS","对话动作_玩家出售囚犯"},
                { "DA_PLAYER_SURRENDER_MEMBER_DIFFERENT_RACE","对话动作_玩家交出不同种族的成员"},
                { "DA_SUMMON_MY_SQUAD","对话动作_召集我的队伍"},
                { "DA_REMOVE_SLAVE_STATUS","对话动作_清除奴隶状态"},
                { "DA_OPEN_NEAREST_GATE","对话动作_打开最近的门"},
                { "DA_ATTACK_STAY_NEAR_HOME","对话动作_在家附近攻击"},
                { "DA_MASSIVE_ALARM","对话动作_巨大的警报"},
                { "DA_ATTACK_IF_NO_COEXIST","对话动作_如果无法共存就攻击"},
                { "DA_KNOCKOUT","对话动作_敲晕"},
                { "DA_END","对话动作_结束"},

                { "DR_NO_LIMIT","对话重复时间_无限制"},
                { "DR_SHORT_2","对话重复时间_2小时"},
                { "DR_MEDIUM_6","对话重复时间_6小时"},
                { "DR_LONG_48","对话重复时间_48小时"},
                { "DR_LONG_1WEEK","对话重复时间_一周"},
                { "DR_ONCE_ONLY","对话重复时间_仅仅一次"},
                { "DR_VSHORT_020","对话重复时间_20分钟"},
              
                { "GROUND_SAND","地面材料_沙子"},
                { "GROUND_GRASS","地面材料_草地"},
                { "GROUND_CONCRETE","地面材料_混凝土"},
                { "GROUND_WOOD","地面材料_木头"},
                { "GROUND_METAL","地面材料_金属"},
                { "GROUND_WATER","地面材料_水"},
                { "GROUND_MUD","地面材料_泥"},
                { "GROUND_SNOW","地面材料_雪"},
                { "GROUND_DIRT","地面材料_污垢"},
               
                { "ITEM_NO_FUNCTION","物品作用_无"},
                { "ITEM_FIRSTAID","物品作用_急救"},
                { "ITEM_MEDRIGGING","物品作用_医疗"},
                { "ITEM_FOOD","物品作用_食物"},
                { "ITEM_CONTAINER","物品作用_容器"},
                { "ITEM_WEAPON","物品作用_武器"},
                { "ITEM_CLOTHING","物品作用_衣服"},
                
                { "ITEM_NARCOTIC","物品作用_麻醉剂"},
                { "ITEM_TOOL","物品作用_工具"},
                { "ITEM_ANYTHING","物品作用_任何"},
                { "ITEM_BLUEPRINT","物品作用_蓝图"},
                { "ITEM_ROBOTREPAIR","物品作用_机器人修理"},
                { "ITEM_BOOK","物品作用_书籍"},
                { "ITEM_MONEY","物品作用_钱"},
                { "ITEM_FOOD_RESTRICTED","物品作用_食物原料"},
                { "ITEM_AMMO","物品作用_弹药"},
                { "ITEM_SEVERED_LIMB","物品作用_断肢"},
               
                { "PERSIST_NONE","卸载当_无"},
                { "PERSIST_INDOORS","卸载当_在室内"},
                { "PERSIST_INTOWN","卸载当_在城内"},
                { "PERSIST_ALWAYS","卸载当_总是"},
            
                { "GROUND","矿产资源_地面"},
              
                { "WALK","移动速度_行走"},
                { "JOG","移动速度_慢跑"},
                { "RUN","移动速度_跑步"},
                { "GROUPED","移动速度_队列"},
                { "NO_SPEED_CHANGE","移动速度_不改变当前速度"},
               
                { "NODE_SHOPKEEPER","节点类型_售货员"},
                { "NODE_GENERAL","节点类型_常规"},
                { "NODE_GUARD_POST","节点类型_防御点"},
                { "NODE_TURRET","节点类型_炮塔"},
                { "NODE_USE","节点类型_使用"},
                { "NODE_LIGHT","节点类型_灯"},
                { "NODE_NULL","节点类型_无"},
                
                { "NAVMESH_IGNORE","路径模式_可以穿过"},
                { "NAVMESH_PROJECTED","路径模式_用于小障碍"},
                { "NAVMESH_OBSTACLE","路径模式_比如绕过用于大物体"},
                { "NAVMESH_WALKABLE","路径模式_可以走在这个建筑之上"},

                { "PT_NONE","性格标签_无"},
                { "PT_HONORABLE","性格标签_高尚"},
                { "PT_TRAITOROUS","性格标签_叛逆"},
                { "PT_SMART","性格标签_聪明"},
                { "PT_DUMB","性格标签_沉默"},
                { "PT_BRAVE","性格标签_勇敢"},
                { "PT_FEARFUL","性格标签_懦弱"},
                { "PT_WARM_KIND","性格标签_温暖善良"},
                { "PT_COLD_CRUEL","性格标签_冷酷残忍"},
                { "PT_NORMAL","性格标签_普通"},
                { "PT_MANIACAL","性格标签_莽撞疯狂"},
                { "PT_END","性格标签_结束"},
               
                { "NOT_SLAVE","初始奴隶状态_不是奴隶"},
                { "IS_SLAVE","初始奴隶状态_是奴隶"},
                { "ESCAPING_SLAVE","初始奴隶状态_逃跑的奴隶"},
                { "EX_SLAVE","初始奴隶状态_以前是奴隶"},

                { "UPJOB_NONE","任务完成后_无"},
                { "UPJOB_PATROL_TOWN","任务完成后_巡逻城市"},
                { "UPJOB_PATROL_SHORTRANGE","任务完成后_短距离巡逻"},
                { "UPJOB_PATROL_LONGRANGE","任务完成后_长距离巡逻"},
                { "UPJOB_GOHOME","任务完成后_回家"},
                { "UPJOB_TRAVEL_TARGET","任务完成后_旅行到目标所在"},
                { "UPJOB_TRAVEL_TARGET_FAST","任务完成后_快速旅行到目标所在"},
             
                { "ASSAULT_TOWN","战役类型_突袭城市"},
                { "CONQUER_TOWN","战役类型_占领城市"},
                { "DEFEND_TOWN","战役类型_防御城市"},
                { "TRADER_VISIT","战役类型_商人访问"},
               
                { "WA_NONE","天气影响_无"},
                { "WA_DUSTSTORM","天气影响_沙尘暴"},
                { "WA_ACID","天气影响_酸雨"},
                { "WA_BURNING","天气影响_灼烧"},
                { "WA_GAS","天气影响_瓦斯"},
                { "WA_RAIN","天气影响_雨"},

                { "SKILL_KATANAS","武器分类_武士刀技能"},
                { "SKILL_SABRES","武器分类_军刀技能"},
                { "SKILL_BLUNT","武器分类_钝器技能"},
                { "SKILL_HEAVY","武器分类_重武器技能"},
                { "SKILL_HACKERS","武器分类_骇客刀技能"},
                { "SKILL_UNARMED","武器分类_武术技能"},
                { "SKILL_BOW","武器分类_弩弓技能"},
                { "SKILL_TURRET","武器分类_炮塔技能"},
                { "ATTACK_POLEARMS","武器分类_长柄武器攻击"},
                { "ATTACK_ELEPHANT","武器分类_象形攻击"},
                { "ATTACK_DOG","武器分类_狗型攻击"},
                { "ATTACK_BULL","武器分类_牛型攻击"},
                { "ATTACK_ROBOTSPIDER","武器分类_机器蜘蛛攻击"},
                { "ATTACK_SPIDER","武器分类_蜘蛛攻击"},
                { "ATTACK_CAGEBEAST","武器分类_野兽攻击"},
  
             

                { "ADD_MATERIALS_TO_BUILDING","为建筑添加材料"},
                { "ALPHA","透明"},
                { "ALWAYS_IMPOSSIBLE_TASK","永不可能完成的任务"},
                { "ANIMAL_FETCH_A_LIMB","动物拿取在肢体"},
                { "ANY","任何"},
                { "AQUIRE_FOOD_AT_HOMEBASE","在基地获取食物"},
                { "ARREST_TARGET","逮捕目标"},
                { "ARREST_TARGETS_CARRIED_PERSON","逮捕目标携带的人"},
                { "ASSAULT_FORTIFICATIONS_PREFER_GATES","攻击防御工事优先大门"},
                { "ASSAULT_FORTIFICATIONS_PREFER_WALLS","攻击防御工事优先城墙"},
                { "ATTACH_BACK","附加背部"},
                { "ATTACH_BACKPACK","附加背包"},
                { "ATTACH_BEARD","附加胡子"},
                { "ATTACH_BELT","附加腰带"},
                { "ATTACH_BODY","附加身体"},
                { "ATTACH_BOOTS","附加脚部"},
                { "ATTACH_EYES","附加眼睛"},
                { "ATTACH_GLOVES","附加手套"},
                { "ATTACH_HAIR","附加头发"},
                { "ATTACH_HAT","附加帽子"},
                { "ATTACH_LEGS","附加退"},
                { "ATTACH_NECK","附加脖子"},
                { "ATTACH_NONE","没有附加"},
                { "ATTACH_SHIRT","附加衬衫"},
                { "ATTACH_WEAPON","附加武器"},
                { "ATTACK_ATTACKERS_OF","攻击谁的攻击者"},
                { "ATTACK_CHARACTERS_ATTACKER","攻击人形攻击者"},
                { "ATTACK_ENEMIES","攻击敌人"},
                { "ATTACK_ENEMIES_AND_NEUTRALS","攻击敌人和中立者"},
                { "ATTACK_ENEMIES_OF_MY_SLAVEMASTER","攻击我奴隶主的敌人"},
                { "ATTACK_TOWN","攻击小镇"},
                { "ATTACK_TROUBLE_MAKERS","攻击麻烦制造者"},
                { "AUTO_LABOURING_MINES","自动矿山劳动"},
                { "AUTO_LABOURING_MINES_PRETEND","假装矿山劳动"},
                { "Armor_Plating","板甲片"},
                { "Armorer","盔甲作坊"},
                { "Attack","攻击"},
                { "BASH_DOOR","踢门"},
                { "BASH_DOOR_HERE","踢这里的门"},
                { "BASH_DOOR_PLAYER_ORDER","命令_踢门"},
                { "BASH_GATE","踢防御门"},
                { "BEAK","喙嘴兽"},
                { "BEAT_CAGE_OCCUPANT","敲击笼子里的人"},
                { "BLUE","蓝色"},
                { "BODYGUARD","保镖"},
                { "BOTH_ARMS","双手"},
                { "BREAKOUT_PRISONER","突破囚徒"},
                { "BROKEN","损坏"},
                { "BRUTE_FORCE_LOCK","蛮力开锁"},
                { "BRUTE_FORCE_SHACKLES","蛮力开脚镣"},
                { "BULL","牛"},
                { "BUY_SHIT","买狗屎"},
                { "Backpack","行囊"},
                { "Bar","酒吧"},
                { "Bed","床上"},
                { "Blue","蓝"},
                { "Blueprints","蓝图"},
                { "Boxes","箱子"},
                { "Building_Material","建筑材料"},
                { "CAGE","笼子"},
                { "CAPTURE_ESCAPING_SLAVES","捕获逃跑的奴隶"},
                { "CAPTURE_NEW_SLAVES","获取新的奴隶"},
                { "CARAVAN","商队"},
                { "CARBON","煤炭"},
                { "CARRY_WOUNDED_SLAVES","抬着受伤的奴隶"},
                { "CHAIN_TARGET","目标链"},
                { "CHASE","追赶"},
                { "CHASE_ALLY_DOGS_WITH_MOUTH_LIMBS","追赶叼着四肢的盟友的狗"},
                { "CHOOSE_ATTACKER_OF_ALLY","选择盟友的攻击者"},
                { "CHOOSE_ENEMY_AND_ATTACK","选择敌人然后进攻"},
                { "CLOSE","关闭"},
                { "CLOSED","已关闭"},
                { "CLOSE_DOOR","关闭门"},
                { "CLOSE_DOOR_HERE","关闭这里的门"},
                { "CLUSTER","群聚"},
                { "COLLECT_OUTPUT_RESOURCE","收集输出的资源"},
                { "COLLECT_OUTPUT_RESOURCE_BUILD_MATS","收集输出资源构建材料"},
                { "CONCRETE","混凝土"},
                { "CONNECTOR","连接器"},
                { "COPPER","铜矿"},
                { "CROSSBOW","弩弓"},
                { "CROSSBOW_TURRET","弩炮塔"},
                { "CROUCH","蹲下"},
                { "CUT_LOCK","砍断锁"},
                { "CUT_SHACKLES","砍断脚镣"},
                { "CYLINDER","圆柱"},
                { "Campfire","篝火"},
                { "Chain_Bench","链甲作坊"},
                { "Cyan","青色"},
                { "DEAD_GUYS_GO_IN_THE_POT","死人扔进锅里_焚尸炉"},
                { "DEFAULT","默认值"},
                { "DEFEAT_SQUAD","击败小队"},
                { "DEFEAT_SQUAD_LIMIT_CHASE_RANGE","溃败小队但限制追击范围"},
                { "DELIVER_RESOURCES","提供资源"},
                { "DISMANTLE","拆除"},
                { "DITCH_ALL_RESOURCES","丢弃所有的资源"},
                { "DOG","狗子"},
                { "DOUBLE_SIDED","双面材质"},
                { "DUCK","鸭子"},
                { "Dummy","假人"},
                { "EAT_A_RANDOM_CAGE_OCCUPANT","吃任意笼子里的一个人"},
                { "EAT_A_RANDOM_CAGE_OCCUPANT_MEASURED_RATE","规律的吃任意笼子里的一个人"},
                { "EAT_A_RANDOM_DEAD_BODY","吃任意已死亡的尸体"},
                { "EAT_A_RANDOM_KO_BODY","吃任意已昏倒尸体"},
                { "EAT_CROPS","吃农作物"},
                { "EAT_FOOD_ON_GROUND","坐地上吃东西"},
                { "EAT_TARGET_ALIVE","吃活着的目标"},
                { "EITHER","任一"},
                { "EMISSIVE","自发光"},
                { "EMPTYING_MACHINE","空着的机器"},
                { "EMPTY_MACHINE_OUTPUTS","没有产出的机器"},
                { "ENTER_BUILDING","进入建筑"},
                { "EQUIP_CROSSBOW","装备弩弓"},
                { "EQUIP_WEAPON","装备武器"},
                { "ESCAPE_KIDNAP","逃脱绑架"},
                { "ESCAPE_KIDNAP_STR","逃脱绑架STR"},
                { "FEED_CORPSE_INTO_MACHINE","把尸体放进机器"},
                { "FILL_MACHINE","填充机器"},
                { "FIND_AND_KIDNAP","找到并绑架"},
                { "FIND_AND_RESCUE","找到并营救"},
                { "FIND_AND_RESCUE_IF_THERES_BEDS","如果有床就去找和营救"},
                { "FIND_AND_RESCUE_LEADER","找到并营救队长"},
                { "FIND_A_DEAD_GUY","找到一个死人"},
                { "FIND_A_SHOP","找到一个商店"},
                { "FIND_BED_AND_PUT_IN","找张床并放下"},
                { "FIND_CAGE_AND_PUT_DEADGUY_IN","找到囚笼并把死人放进去"},
                { "FIND_CAGE_AND_PUT_IN","找到囚笼并放进去"},
                { "FIND_CAGE_AND_PUT_IN_IF_BOUNTY","如果他有赏金则找到囚笼并把他放进去"},
                { "FIND_CROPS_TO_EAT","找农作物吃"},
                { "FIND_SOME_BUILDING_MATERIALS","找一些建筑材料"},
                { "FIND_WEAPON","寻找武器"},
                { "FIRST_AID_ORDER","命令_急救"},
                { "FIRST_AID_ROBOT","急救机器人"},
                { "FLICKER","闪烁"},
                { "FOCUSED_MELEE_ATTACK","集中近战攻击"},
                { "FOGMAN_WORSHIP_VICTIM","雾人崇拜祭品"},
                { "FOLIAGE","植被"},
                { "FOLLOW_PLAYER_ORDER","命令_跟随玩家"},
                { "FOLLOW_SLAVEMASTER","跟随奴隶商"},
                { "FOLLOW_SQUADLEADER","跟随小队长"},
                { "FOLLOW_URGENT_ESCAPE","遵循紧急逃生"},
                { "FOLLOW_WHILE_TALKING","说话时跟随"},
                { "FORCE_GET_UP","强制起立"},
                { "GARRU","加鲁兽"},
                { "GATHER_SLAVES_FROM_CAGES","把奴隶从笼子里抓起来"},
                { "GATHER_SLAVES_FROM_CAGES_IF_FEMALE_OR_BEAST","如果是女人或野兽就把奴隶从笼子里抓出来"},
                { "GATHER_SLAVES_FROM_CAGES_IF_ITS_AN_EXPORT_TOWN","如果是个出口城市就把奴隶从笼子里抓出来"},
                { "GET_NEAR_TO","接近"},
                { "GET_OUT_OF_BED","从床上下来"},
                { "GET_OUT_OF_BED_IF_ITS_EMERGENCY","如果有紧急情况就起床"},
                { "GET_OUT_OF_BED_ONCE_HEALED","伤好后后马上起床"},
                { "GET_OUT_OF_CAGE_ESCAPE","逃出囚笼"},
                { "GET_OUT_OF_CAGE_LEGIT","合法地从笼子里出来"},
                { "GET_OUT_OF_CAGE_OPPORTUNISTIC","冒风险的逃出牢笼"},
                { "GET_PUT_IN_BED","放在床上"},
                { "GET_READY_FOR_ACTION","准备好行动"},
                { "GET_RE_EQUIPPED","重新装备武器"},
                { "GET_RID_OF_RESOURCES_IN_MY_INVENTORY","清空我的库存"},
                { "GET_UP","起来"},
                { "GIVE_ALL_MY_SLAVES_TO","把我所有的奴隶都给"},
                { "GIVE_ALL_MY_SLAVES_TO_IF_ITS_AN_IMPORT_TOWN","如果是进口城市就把我所有的奴隶都给"},
                { "GOAT","山羊"},
                { "GORILLO","喙嘴猩猩"},
                { "GO_HOMEBUILDING","回自己家"},
                { "GO_HOME_AND_GO_TO_BED","回家并睡觉"},
                { "GO_HOME_AND_GO_TO_BED_SECURE","回家并安心睡觉"},
                { "GO_TO_NEAREST_HQ","去最近的总部"},
                { "GO_TO_SOMEWHERE_FOR_DELIVERING_SLAVES","去能交付奴隶的地方"},
                { "GO_TO_THE_BAR_AND_DRINK","去酒吧喝酒"},
                { "GRAB_ONE_FOOD","夺取一个食物"},
                { "GREEN","绿色"},
                { "GRID","网格1"},
                { "Gate","大门"},
                { "General_Goods","一般商品"},
                { "Generator","发电机"},
                { "Grain_Silo","粮仓"},
                { "Green","绿"},
                { "HARPOON_GUN","鱼叉枪"},
                { "HARPOON_TURRET","鱼叉炮塔"},
                { "HEAD = 8","头部 = 8"},
                { "HEAL_MY_LEGS","治疗我的腿"},
                { "HIVE","蜂人"},
                { "HOLD_POSITION","坚守岗位"},
                { "HUMAN","人类"},
                { "HUNTING_BLOODSMELL","根据血腥味狩猎"},
                { "HUNT_BOUNTIES","狩猎赏金犯人"},
                { "HUNT_MY_THIEF","猎杀偷过我的小偷"},
                { "Hive_Hut","蜂巢小屋"},
                { "House","房子"},
                { "IDLE","空闲"},
                { "IGNORE","忽略"},
                { "INVESTIGATE_ALARMS","调查警报处"},
                { "INVESTIGATE_ALARMS_ALLIES_ONLY","调查警报处_只盟友"},
                { "IRON","铁矿"},
                { "IRONSPIDER","铁蜘蛛"},
                { "JOB_BUILDER","工作_工程师"},
                { "JOB_KEEP_EVERYTHING_RUNNING","工作_保证一切运转"},
                { "JOB_MEDIC","工作_医生"},
                { "JOB_REPAIR_ROBOT","工作_修理机器人"},
                { "KIDNAP_ORDER","命令_绑架"},
                { "KILL_A_RANDOM_CAGE_OCCUPANT","杀任意笼子里的一个人"},
                { "KILL_CAGE_OCCUPANT","杀死笼子里的人"},
                { "KNOCKOUT_PRISONER","敲晕囚犯"},
                { "LEAVE_BUILDING","离开建筑"},
                { "LEFT_ARM","左手"},
                { "LEFT_ARM = 4","左手 = 4"},
                { "LEFT_ARM = 50"," 左臂= 50 "},
                { "LEFT_LEG","左脚"},
                { "LEFT_LEG = 32","左脚 = 32"},
                { "LEFT_LEG = 52","左腿 = 52"},
                { "LEVIATHAN","利维坦"},
                { "LIBERATE_ALL_THE_PRISONERS","释放所有的囚犯"},
                { "LIFT_OBJECT_BUT_HEAL_FIRST","举起物体但先治愈"},
                { "LIFT_PERSON","举起人"},
                { "LIFT_PERSON_PLAYER_ORDER","命令_举起人"},
                { "LIFT_PERSON_SNATCHING_ALLOWED","举起人_允许抢劫"},
                { "LIFT_PERSON_SNATCHING_ALLOWED_IN_TOWN_ONLY","举起人_只限城市"},
                { "LOCKED","已上锁"},
                { "LOCK_ALL_MY_DOORS","锁上我所有的门"},
                { "LOCK_ALL_MY_DOORS_FROM_OUTSIDE","从外面锁上我所有的门"},
                { "LOCK_ALL_THE_CAGES","锁上我所有的囚笼"},
                { "LOCK_DOOR","锁上门"},
                { "LOCK_DOOR_FROM_INSIDE","从里面锁门"},
                { "LOCK_DOOR_FROM_OUTSIDE","从外面锁门"},
                { "LOCK_DOOR_HERE","锁这里的门"},
                { "LOOT_ANIMALS_JOB","工作_摸动物尸体"},
                { "LOOT_CONTAINER","战利品容器"},
                { "LOOT_FOOD_AND_STUFF","掠夺食物和东西"},
                { "LOOT_RESOURCE_ITEMS_WE_HAVE_STORAGE_FOR","'掠夺我们有存储容器的资源'"},
                { "LOOT_STOLEN_GOODS","掠夺赃物"},
                { "LOOT_TARGET","掠夺目标"},
                { "LOOT_THE_DEAD","掠夺死人"},
                { "LOOT_TO_REPLACE_MISSING_WEAPON","掠夺并装配没有的武器"},
                { "Lamp","灯具"},
                { "Leather","皮格"},
                { "Luxury","奢侈品"},
                { "MAKE_ANNOUNCEMENT","发表声明"},
                { "MAKE_ANNOUNCEMENT_FAST","快速发表声明"},
                { "MAKE_TARGET_STAND_STILL","让目标静止站立"},
                { "MAN_A_TURRET","操作炮塔"},
                { "MAN_A_TURRET_ON_BUILDING","操作建筑上的炮塔"},
                { "MAN_A_TURRET_PLAYER_JOB","玩家工作_操作炮塔"},
                { "MAN_THE_GATE","看守大门"},
                { "MATERIAL_CHAIN","链甲材料"},
                { "MATERIAL_CLOTH","布质材料"},
                { "MATERIAL_LEATHER","皮革材料"},
                { "MATERIAL_METAL_PLATE","板甲材料"},
                { "MELEE_ATTACK","近战攻击"},
                { "MELEE_ATTACK_ANIMAL","近战攻击动物"},
                { "METAL","金属材料"},
                { "MILITARY","军队"},
                { "MISSION_ESCORT","保护任务"},
                { "MISSION_NULL","空任务"},
                { "MOVE_INSIDE_BUILDING","移动到建筑内"},
                { "MOVE_TO_BUILDING_DOOR","移动到建筑门口"},
                { "MOVE_TO_BUILDING_DOOR_INSIDEPOS","移动到建筑门后"},
                { "MOVE_TO_BUILDING_DOOR_OUTSIDEPOS","移动到建筑门外"},
                { "MOVE_TO_CURRENT_LOCATION_BUILDING_DOOR","移动到当前位置建筑的门"},
                { "MOVE_TO_FORTIFICATION_GATE","移到防御工事门口"},
                { "Magenta","洋红"},
                { "Mechanical","机械的"},
                { "Metal","金属的"},
                { "NEW_SLAVE_PROCESSING","新奴隶处理中"},
                { "NO","不"},
                { "NONE","不存在"},
                { "NONE = 0","不存在 = 0"},
                { "NORMAL","正常"},
                { "NOT_BE_UNARMED","不是手无寸铁的"},
                { "NULL_LIMB","无肢体"},
                { "NULL_TASK","无任务"},
                { "Narcotics","毒品"},
                { "None","不存在的"},
                { "OBSTACLE","障碍物"},
                { "OPEN","打开"},
                { "OPEN_DOOR","对开门"},
                { "OPEN_DOOR_FOR_CURRENT_LOCATION","打开当前位置的门"},
                { "OPEN_DOOR_FOR_DESTINATION","打开目的地的门"},
                { "OPEN_DOOR_HERE","打开这里的门"},
                { "OPEN_FORTIFICATION_GATE","打开防御门"},
                { "OPEN_UP_SHOP_DOORS","开门营业"},
                { "OPERATE_AUTOMATIC_MACHINERY","操作自动化的机器"},
                { "OPERATE_MACHINERY","操作机器"},
                { "OPERATE_STORAGE","操作存储器"},
                { "Orange","橙"},
                { "PACK","驮兽"},
                { "PART_ARM","手臂部分"},
                { "PART_HEAD","头部分"},
                { "PART_LEG","腿部分"},
                { "PART_TORSO","躯干部分"},
                { "PATROL","巡逻"},
                { "PATROL_TOWN","巡逻城市"},
                { "PICKUP","捡起来"},
                { "PICKUP_INTRUDERS","捡起入侵者"},
                { "PICKUP_INTRUDERS_TOWN","建起城市入侵者"},
                { "PICK_LOCK","撬开锁"},
                { "PICK_LOCK_ON_SHACKLES","撬开脚镣上的锁"},
                { "PLAYER_TALK_TO","玩家交谈与"},
                { "PLAY_BECAUSE_I_HAVE_A_LIMB_IN_MOUTH","玩因为我嘴里有条腿"},
                { "POINT","点"},
                { "POINT_LIGHTING","点照明"},
                { "POLICE_FREE_PRISONERS_WHEN_DONE","警察释放刑期到的犯人"},
                { "PRETEND_TO_OPERATE_MACHINERY","假装操作机器"},
                { "PROCESS_AND_STRIP_NEW_SLAVE","处理并剥去新奴隶"},
                { "PROJECTED","投影"},
                { "PROSPECTING","勘探"},
                { "PROTECTION","保护"},
                { "PROTECT_ALLIES","保护盟友"},
                { "PROTECT_ALLIES_STAY_IN_TOWN","保护城里的盟友"},
                { "PROTECT_OWN_SQUAD","保护自己小队"},
                { "PULSE","脉冲"},
                { "PUT_DOWN_CARRIED_DUDE_IF_THEY_CAN_WALK","如果携带的人能走_就放下他"},
                { "PUT_DOWN_CHARACTER_IN_BED","把携带的角色放在床上"},
                { "PUT_DOWN_OBJECT","放下对象"},
                { "PUT_IN_CAGE","放在笼子里"},
                { "PUT_LOOT_IN_STORAGE","把赃物放仓库"},
                { "PUT_SOMEONE_IN_BED","把某人放上床"},
                { "Potato","土豆"},
                { "Purple","紫"},
                { "QUELL_AGGRESSION","平息侵略"},
                { "RAID_TOWN","突袭城镇"},
                { "RANDOM","随机"},
                { "RANGED_ATTACK","远程攻击"},
                { "RANGED_ATTACK_FOCUSED","远程攻击集中"},
                { "RANGED_ATTACK_FOCUSED_UNPROVOKED","无端远程攻击"},
                { "RECRUIT_AT_JOBCENTER","在JOBCENTER招募"},
                { "RED","红色"},
                { "RELAX_IN_TOWN_PACKAGE","在城内放松休息"},
                { "RELEASE_PRISONER","释放囚犯"},
                { "RELOAD","重新加载"},
                { "REPAIR","修复"},
                { "REST","休息"},
                { "RETREAT_HOMETOWN","撤退回家"},
                { "RIGHT_ARM","右手"},
                { "RIGHT_ARM = 2","右手= 2"},
                { "RIGHT_ARM = 51","右臂= 51"},
                { "RIGHT_LEG","右脚"},
                { "RIGHT_LEG = 16","右脚 = 16"},
                { "RIGHT_LEG = 53","右腿 = 53"},
                { "RUN_AROUND_TOWN_LOOKING_FOR_PEOPLE","在城里到处找人"},
                { "RUN_AWAY","逃跑"},
                { "RUN_AWAY_FORCED","强制逃跑"},
                { "RUN_AWAY_HOMETOWN","逃离家乡"},
                { "Red","红"},
                { "Research_Bench","研究台"},
                { "Robotic_Component","机器人组件"},
                { "Rum","朗姆酒"},
                { "SAND","沙子"},
                { "SEEK_AND_TALK_AND_SEND_SIGNAL","寻找_交谈_发送信号"},
                { "SELF_PRESERVATION","自保"},
                { "SEND_DIALOGUE_SIGNAL","发出对话信号量"},
                { "SEND_DIALOGUE_SIGNAL_REPEAT","重复发送对话信号"},
                { "SEND_DIALOGUE_SIGNAL_WITHOUT_MOVING","发出对话信号量但不移动"},
                { "SHEK","史克"},
                { "SHIMMER","微光"},
                { "SHOOT_AT_TARGET","射击目标"},
                { "SHOO_STRANGERS_OUT_OF_MY_BUILDING","把陌生人赶出我的建筑"},
                { "SHOO_STRANGERS_OUT_OF_MY_BUILDING_IF_PRIVATE","把陌生人赶出我的私有建筑"},
                { "SHOPPING","购物"},
                { "SINGLE","单一"},
                { "SIT_AROUND","无所事事"},
                { "SIT_ON_THRONE","坐在宝座上"},
                { "SKELETON","骨人"},
                { "SLAVE_GET_IN_MY_MASTERS_CAGE","奴隶进主人的笼子"},
                { "SLAVE_WATCHING","看管奴隶"},
                { "SLEEP_ON_FLOOR","睡在地板上"},
                { "SLEEP_ON_FLOOR_FAKE_AMBUSH","睡在地板上假装埋伏"},
                { "SMASH_BUILDING","粉碎建筑"},
                { "SNOW","雪"},
                { "SPHERE","球体"},
                { "SPIDER","蜘蛛"},
                { "SPLINT_JOB","工作_夹板"},
                { "SPLINT_ORDER","命令_夹板"},
                { "SPOT","灯光照射"},
                { "SQUAD_WAIT_FOR_ME","队伍等待我"},
                { "STAND_AT_BUILDING_DEFENSIVE_NODE","站在建筑的防御节点"},
                { "STAND_AT_BUILDING_GUARD_NODE","站在建筑的守卫节点"},
                { "STAND_AT_DEFENSIVE_NODE","站在防御节点"},
                { "STAND_AT_GENERAL_NODE","站在普通节点"},
                { "STAND_AT_GUARD_NODE_HOMEBUILDING","'站在家里建筑的守卫节点'"},
                { "STAND_AT_GUARD_NODE_HOMEBUILDING_INDOORS_ONLY","只站在家里建筑门内的守卫节点"},
                { "STAND_AT_GUARD_NODE_HOMETOWN_OUTSIDE","站在城市外的守卫节点"},
                { "STAND_AT_NODE","站在节点"},
                { "STAND_AT_SHOPKEEPER_NODE","站在售货员节点"},
                { "STAND_STILL","一直站着"},
                { "STAND_UP","站起来"},
                { "STAY_CLOSE_TO_TARGET","靠近目标"},
                { "STAY_IN_HOME","呆在家里"},
                { "STEALTH_KILL","隐形暗杀"},
                { "STEALTH_KNOCKOUT","潜行击倒"},
                { "STONE","石材"},
                { "STRIP_TARGETS_WEAPONS","卸掉目标武器"},
                { "STUMBLE_TASK_FORCED","强制跌倒任务"},
                { "SWITCH_FOLLOW_ME_MODE_ON","开启跟随我模式"},
                { "Shop_Counter","商店的柜台"},
                { "Smithy","铁匠"},
                { "Steel_Bar","钢筋"},
                { "Stone","石头"},
                { "Stone_Processor","石头处理器"},
                { "Store_Armor","储存盔甲"},
                { "Store_Building_Materials","储存建筑材料"},
                { "Store_Flour","储存面粉"},
                { "Store_Ore","储存矿石"},
                { "Store_Prisoner","储存囚犯"},
                { "Store_Rum","储存酒"},
                { "Store_Stones","储存石头"},
                { "TAKE_INTRUDER_OUTSIDE","把闯入者带到门外"},
                { "TAKE_INTRUDER_OUTSIDE_TOWN","把闯入者带到城外"},
                { "TAKE_OFF_MY_SHACKLES","脱下我的脚镣"},
                { "TALKTO_NEAREST_PLAYER_CHARACTER","与最近的玩家角色交谈"},
                { "TARGET_HOME_GATE","目标家里的门"},
                { "TARGET_LEADER","目标领袖"},
                { "TARGET_SELF","目标自己"},
                { "TARGET_SPECIFIC","特定目标"},
                { "TARGET_SQUAD_MISSION","目标队伍的任务"},
                { "TEE_NOTHING","什么也不做"},
                { "TEE_REMOVE_MINE_ONLY","只移除我自己'"},
                { "TEE_REMOVE_WHOLE_SQUADS","移除整个小队"},
                { "TERRAIN","地形"},
                { "TERRITORIAL_AGGRESSION_BUT_DONT_LEAVE_HOME","领土侵犯_但不要离开家"},
                { "TOTAL_ESCAPE","彻底逃逸"},
                { "TOWN_STALKER","城镇潜行"},
                { "TRAVEL_TO_TARGET_TOWN","前往目标城市"},
                { "TRAVEL_TO_TARGET_TOWN_FAST","快速前往目标城市"},
                { "TURTLE","海龟"},
                { "Tailor","裁缝"},
                { "Tarsands","焦油砂"},
                { "Tools","工具"},
                { "Tower","塔"},
                { "Travel","旅行"},
                { "Turret","炮塔"},
                { "UNEQUIP_CROSSBOW","收回弩"},
                { "UNEQUIP_WEAPON","收回武器"},
                { "UNJAM_ALL_MACHINES","加入所有机器"},
                { "UNJAM_MACHINE","插入机器"},
                { "UNLOCK_DOOR","撬开门"},
                { "UNLOCK_DOOR_HERE","撬开这里的们"},
                { "UNLOCK_DOOR_PLAYER_ORDER","玩家命令_撬开门锁"},
                { "UNPROVOKED_FOCUSED_MELEE_ATTACK","无故集中肉搏攻击"},
                { "USE_BED","使用床"},
                { "USE_BED_ORDER","命令_使用床"},
                { "USE_CAGE","使用囚笼"},
                { "USE_TRAINING_DUMMY","使用训练假人"},
                { "USE_TURRET","使用炮塔"},
                { "UV_MAPPED","UV映射"},
                { "WALKABLE","可行走"},
                { "WANDERER","想要从一个城市到另一个城市"},
                { "WANDERING","漫游"},
                { "WANDERING_TRADER","想要购物"},
                { "WANDER_TOWN","漫游去城市"},
                { "WANT_TO_FILL_MACHINE","想要填充机器"},
                { "WATER","水资源"},
                { "WHOLE = 1","整个 = 1"},
                { "WOOD","木头"},
                { "WORK_THE_SLAVES","奴隶的工作"},
                { "WORSHIP_TARGET","崇拜目标"},
                { "Wall_Metal","金属墙"},
                { "Wall_Station_House","墙警察局"},
                { "Wall_Stone","石头墙"},
                { "Wall_Wood","木头墙"},
                { "Water","水"},
                { "Well","水井"},
                { "Wheat","小麦"},
                { "White","白"},
                { "Wicker","藤条"},
                { "Wind_Generator","风力发电机"},
                { "Wood","木材"},
                { "Wood_Object_Big","大木材对象"},
                { "Wood_Object_Small","小木材对象"},
                { "X_AXIS","X轴"},
                { "YES","是"},
                { "Y_AXIS","Y轴"},
                { "Yellow","黄"},
                { "Z_AXIS","Z轴"},
                
            };

        }

        public static string getTransValue(string oldString)
        {
            string tansedStr = null;
            if ((bool)NativeTranslte.enumDict.TryGetValue(oldString, out tansedStr))
            {
                return tansedStr;
            }
            return oldString;
        }

        public static string getTransSection(string oldString)
        {
            string tansedStr = null;
            if ((bool)NativeTranslte.sectionDict.TryGetValue(oldString, out tansedStr))
            {
                return tansedStr;
            }
            return oldString;
        }
        public static string getTransEvent(string oldString)
        {
            string tansedStr = null;
            if ((bool)NativeTranslte.eventDict.TryGetValue(oldString, out tansedStr))
            {
                return tansedStr;
            }
            return oldString;
        }

        [DllImport("shell32.dll")]
        public extern static IntPtr ShellExecute(int hwnd, string lpOperation, string lpFile, string lpParameters, string lpDirectory, int nShowCmd);
        public enum ShowWindowCommands : int
        {
            SW_HIDE = 0,
            SW_SHOWNORMAL = 1,
            SW_NORMAL = 1,
            SW_SHOWMINIMIZED = 2,
            SW_SHOWMAXIMIZED = 3,
            SW_MAXIMIZE = 3,
            SW_SHOWNOACTIVATE = 4,
            SW_SHOW = 5,
            SW_MINIMIZE = 6,
            SW_SHOWMINNOACTIVE = 7,
            SW_SHOWNA = 8,
            SW_RESTORE = 9,
            SW_SHOWDEFAULT = 10,
            SW_MAX = 10
        }
        public NativeTranslte()
        {
        }
    }
}
