using System;

namespace forgotten_construction_set
{
	public enum WeaponCategory
	{
		SKILL_KATANAS,
		SKILL_SABRES,
		SKILL_BLUNT,
		SKILL_HEAVY,
		SKILL_HACKERS,
		SKILL_UNARMED,
		SKILL_BOW,
		SKILL_TURRET,
		ATTACK_POLEARMS,
		ATTACK_ELEPHANT,
		ATTACK_DOG,
		ATTACK_BULL,
		ATTACK_ROBOTSPIDER,
		ATTACK_SPIDER,
		ATTACK_CAGEBEAST,
		ATTACK_DUCK,
		ATTACK_GORILLA,
		ATTACK_GAR,
		ATTACK_FROG,
		ATTACK_GOAT,
		ATTACK_GIRAFFE,
		ATTACK_NULL,
		NUM_SKILL_TYPES
	}
}