using System;

namespace forgotten_construction_set
{
	public enum BlackboardSignalFunctions
	{
		SIGNAL_NONE,
		SIG_RETREAT_CANNIBAL_RAID,
		SIG_AT_SAFE_TOWN,
		SIG_AT_HOME_TOWN,
		SIG_CANNIBAL_START_PATROL,
		SIG_SQUAD_NOT_INTACT,
		SIG_START_PATROL,
		SIG_DIPLOMAT_MISSION,
		SIG_DEFEAT_SQUAD,
		SIG_HOME_OWNER_KEEP_LOCKED,
		SIG_GATHER_UP_ALL_LOCAL_PRISONERS,
		SIG_SLAVER_SHIP_TO_WORKCAMPS,
		SIG_BODYGUARD,
		SIG_BECOME_EX_SLAVE,
		SIG_OUT_OF_DANGER,
		SIG_DEFEND_PLAYER_TOWN_TIMED,
		SIG_WANDERING_TOWN_TO_TOWN,
		SIG_HANG_OUT_AT_BAR,
		SIG_RAIDING_WEAK_VILLAGES,
		WAR_GATHER_FORCES,
		WAR_ASSAULT_TOWN,
		WAR_BATTLE_MEETING,
		SIG_REFUGEE_DISBAND,
		SIG_START_PATROL_RUNNING,
		SIG_GATHER_UP_ALL_LOCAL_PRISONERS_UNHOLY,
		SIG_RETREAT_CANNIBAL_RAID_TO_NEAREST_NEST,
		SIG_HANG_OUT_OUTDOORS_ONLY,
		SIG_CANNIBALS_AT_HOME,
		SIG_SLAVER_SHIP_TO_ANYWHERE_CLOSE,
		SIG_PASSING_BY_TOWN_ASSAULT,
		SIG_OCCUPY_CONQUERED_TOWN,
		SIG_DEFEND_PLAYER_TOWN_CAMPAIGN,
		WAR_ASSAULT_TOWN_CANNIBAL,
		SIG_TIMED_CONTRACT
	}
}