using System;

namespace forgotten_construction_set
{
	public enum BuildingClassType
	{
		BCTYPE_FLUFF,
		BCTYPE_DOOR,
		BCTYPE_USABLE,
		BCTYPE_STORAGE,
		BCTYPE_PRODUCTION,
		BCTYPE_RESEARCH,
		BCTYPE_CRAFTING,
		BCTYPE_GATEWAY,
		BCTYPE_TURRET,
		BCTYPE_WALL,
		BCTYPE_ITEM_FURNACE,
		BCTYPE_LIGHT,
		BCTYPE_SHELL_WITH_INTERIOR,
		BCTYPE_FARM,
		BCTYPE_BOATHULL
	}
}