using System;

namespace forgotten_construction_set
{
	public enum BuildingFunction
	{
		BF_ANY,
		BF_MINE,
		BF_RESOURCE_STORAGE,
		BF_RESEARCH,
		BF_REFINERY,
		BF_GENERATOR,
		BF_BED,
		BF_TRAINING,
		BF_CAGE,
		BF_SHOP,
		BF_CRAFTING,
		BF_CORPSE_DISPOSAL,
		BF_TURRET,
		BF_GENERAL_STORAGE,
		BF_ITEM_FURNACE,
		BF_LIGHT,
		BF_TABLE,
		BF_CHAIR,
		BF_FLUFF,
		BF_SHELL_WITH_INTERIOR,
		BF_WALL,
		BF_GATE,
		BF_DOOR,
		BF_BATTERY,
		BF_THRONE,
		BF_SKELETON_BED,
		BF_RAIN_COLLECTOR,
		BF_MINE_NATURAL,
		BF_PROPELLER,
		BF_ENGINE,
		BF_LIQUID_TANK,
		BF_BOATHULL,
		BF_CONTROL_STEERING,
		BF_ALTERNATOR,
		BF_ENGINE_STARTER,
		BF_GENERATOR_WIND
	}
}