using System;

namespace forgotten_construction_set
{
	public enum CrimeEnum
	{
		CRIME_NONE,
		CRIME_ENSLAVING,
		CRIME_LOCKPICKING,
		CRIME_STEALING,
		CRIME_MURDER,
		CRIME_ASSAULT,
		CRIME_ASSAULT_VIP,
		CRIME_SLAVE_FREEING,
		CRIME_SMUGGLING,
		CRIME_TERRORISM,
		CRIME_LOOTING,
		CRIME_TRESSPASSING,
		CRIME_ESCAPE_PRISON,
		CRIME_FENCING,
		CRIME_FARM_EATING,
		CRIME_KIDNAPPING,
		CRIME_UNIFORM_THEFT,
		CRIME_END
	}
}